# Generated by Django 5.2.17 on 2026-08-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.CharField(max_length=64, unique=True, verbose_name='測定ID')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員ID')),
                ('customer_name', models.CharField(db_index=True, max_length=100, verbose_name='お名前')),
                ('member_number', models.CharField(blank=True, max_length=32, verbose_name='会員番号')),
                ('measured_on', models.DateField(db_index=True, verbose_name='測定日')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='ウエスト(cm)')),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='ヒップ(cm)')),
                ('thigh_right', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='太もも右(cm)')),
                ('thigh_left', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='太もも左(cm)')),
                ('whr', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='WHR')),
                ('staff_memo', models.TextField(blank=True, verbose_name='スタッフメモ')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '計測記録',
                'verbose_name_plural': '計測記録',
                'ordering': ['customer_name', 'measured_on'],
                'indexes': [models.Index(fields=['customer_name', 'measured_on'], name='measurement_custome_83f352_idx')],
            },
        ),
    ]
