# Generated by Django 5.2.17 on 2026-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('メニュー', 'メニュー'), ('商品', '商品')], db_index=True, max_length=16, verbose_name='種別')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('recorded_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='記録日')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='単価（円）')),
                ('unit_cost', models.IntegerField(blank=True, null=True, verbose_name='原価（円・1つあたり）')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '売上',
                'verbose_name_plural': '売上',
                'ordering': ['-recorded_on', 'kind', 'sheet_row'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'sheet_row'), name='売上は種別と行で一意')],
            },
        ),
    ]
