# Generated by Django 5.2.17 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='原価（円・1つあたり）'),
        ),
        migrations.AlterField(
            model_name='revenuerecord',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='単価（円）'),
        ),
    ]
