# Generated by Django 5.2.17 on 2026-08-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pushnotice_supportfaq'),
        ('records', '0002_alter_revenuerecord_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='商品名（完全一致）')),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='仕入値（円）')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_prices', to='content.product', verbose_name='結びついた商品')),
            ],
            options={
                'verbose_name': '仕入値',
                'verbose_name_plural': '仕入値',
                'ordering': ['sheet_row'],
            },
        ),
    ]
