# Generated by Django 5.2.17 on 2026-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_supplierprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('happened_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='日時')),
                ('kind', models.CharField(db_index=True, max_length=64, verbose_name='種別')),
                ('result', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='結果')),
                ('target', models.TextField(blank=True, verbose_name='対象')),
                ('summary', models.TextField(blank=True, verbose_name='概要')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='操作者')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='詳細')),
                ('detail_raw', models.TextField(blank=True, verbose_name='詳細（読めなかったもの）')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
            ],
            options={
                'verbose_name': '操作履歴',
                'verbose_name_plural': '操作履歴',
                'ordering': ['-happened_at', '-sheet_row'],
                'indexes': [models.Index(fields=['kind', '-happened_at'], name='records_aud_kind_ead120_idx')],
            },
        ),
    ]
