# Generated by Django 5.2.17 on 2026-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='operator',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='操作者'),
        ),
    ]
