# Generated by Django 5.2.17 on 2026-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_auditlog_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='作成日時')),
                ('kind', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='種別')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='ファイル名')),
                ('file_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ファイルID')),
                ('url', models.TextField(blank=True, verbose_name='URL')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
            ],
            options={
                'verbose_name': '控えの記録',
                'verbose_name_plural': '控えの記録',
                'ordering': ['-created_at', '-sheet_row'],
            },
        ),
    ]
