# Generated by Django 5.2.17 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_backuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員ID')),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='お名前')),
                ('response_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='回答ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('before_photos', models.JSONField(blank=True, null=True, verbose_name='ビフォー写真')),
                ('after_photos', models.JSONField(blank=True, null=True, verbose_name='アフター写真')),
                ('photos_raw', models.TextField(blank=True, verbose_name='写真（読めなかったもの）')),
                ('status', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='分析状態')),
                ('result', models.TextField(blank=True, verbose_name='分析結果')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析日時')),
                ('error', models.TextField(blank=True, verbose_name='エラー')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
            ],
            options={
                'verbose_name': '回数券分析',
                'verbose_name_plural': '回数券分析',
                'ordering': ['-submitted_at', '-sheet_row'],
            },
        ),
    ]
