# Generated by Django 5.2.17 on 2026-08-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_ticketanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='鍵')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='値')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='覚え書き')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': 'アプリの設定',
                'verbose_name_plural': 'アプリの設定',
                'ordering': ['key'],
            },
        ),
    ]
