# Generated by Django 5.2.17 on 2026-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='sheet_row',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='シートの行'),
        ),
    ]
