# Generated by Django 5.2.17 on 2026-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_auditlog_sheet_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='シートの行')),
                ('order_id', models.CharField(db_index=True, max_length=64, verbose_name='注文ID')),
                ('ordered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='注文日時')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='注文者名')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='商品名')),
                ('quantity', models.IntegerField(default=0, verbose_name='個数')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='単価')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='仕入値')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小計')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='純利益')),
                ('total_label', models.CharField(blank=True, max_length=32, verbose_name='合計金額')),
                ('payment', models.CharField(blank=True, max_length=64, verbose_name='支払方法')),
                ('status', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ステータス')),
                ('received', models.BooleanField(default=False, verbose_name='受取確認')),
                ('internal_note', models.TextField(blank=True, verbose_name='管理メモ')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'ordering': ['-ordered_at', 'order_id', 'id'],
                'indexes': [models.Index(fields=['order_id', 'id'], name='records_ord_order_i_384ad5_idx')],
            },
        ),
    ]
