# Generated by Django 5.2.17 on 2026-09-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('opening_balance', models.IntegerField(default=0, verbose_name='前葉繰越')),
            ],
            options={
                'verbose_name': '現金出納帳',
                'verbose_name_plural': '現金出納帳',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uq_cashbook_year_month')],
            },
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('row_order', models.IntegerField(verbose_name='並び順')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='日付（月）')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='日付（日）')),
                ('description', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('counter_account', models.CharField(blank=True, default='', max_length=100, verbose_name='相手科目')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='収入金額')),
                ('payment', models.IntegerField(blank=True, null=True, verbose_name='支払金額')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='keihi.cashbook', verbose_name='帳簿')),
            ],
            options={
                'verbose_name': '現金出納帳の行',
                'verbose_name_plural': '現金出納帳の行',
                'ordering': ['row_order', 'id'],
            },
        ),
    ]
