# Generated by Django 5.2.17 on 2026-09-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keihi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image_name', models.CharField(blank=True, default='', max_length=200, verbose_name='写真のファイル名')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500, verbose_name='元のファイル名')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('store_name', models.CharField(blank=True, default='', max_length=255, verbose_name='店名・支払先')),
                ('counter_account', models.CharField(blank=True, default='', max_length=100, verbose_name='相手科目')),
                ('kind', models.CharField(choices=[('payment', '支払'), ('income', '収入')], default='payment', max_length=10, verbose_name='種別')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('status', models.CharField(choices=[('pending', '読み取り待ち'), ('done', '読み取り済み'), ('failed', '読み取れなかった'), ('manual', '手入力')], default='pending', max_length=10, verbose_name='状態')),
                ('error', models.TextField(blank=True, default='', verbose_name='読み取れなかった理由')),
                ('raw', models.TextField(blank=True, default='', verbose_name='AI の返事（そのまま）')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='keihi.cashbookentry', verbose_name='出納帳の行')),
            ],
            options={
                'verbose_name': 'レシート',
                'verbose_name_plural': 'レシート',
                'ordering': ['date', 'id'],
            },
        ),
    ]
