# Generated by Django 5.2.17 on 2026-09-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keihi', '0002_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('row_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='品名')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keihi.receipt', verbose_name='レシート')),
            ],
            options={
                'verbose_name': 'レシートの品物',
                'verbose_name_plural': 'レシートの品物',
                'ordering': ['row_order', 'id'],
            },
        ),
    ]
