# Generated by Django 5.2.17 on 2026-09-16 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('planning', '計画中'), ('in_progress', '進行中'), ('completed', '完了'), ('suspended', '中断')], default='in_progress', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('discord_webhook_url', models.URLField(blank=True, help_text='設定するとタスク割当時にDiscordへ通知されます', max_length=500, verbose_name='Discord Webhook URL')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_projects', to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
            ],
            options={
                'verbose_name': '開発プロジェクト',
                'verbose_name_plural': '開発プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('status', models.CharField(choices=[('open', '未着手'), ('in_progress', '作業中'), ('review', 'レビュー中'), ('done', '完了'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '緊急')], default='medium', max_length=10, verbose_name='優先度')),
                ('category', models.CharField(choices=[('feature', '機能追加'), ('bug', 'バグ修正'), ('refactor', 'リファクタ'), ('docs', 'ドキュメント'), ('test', 'テスト'), ('infra', 'インフラ'), ('other', 'その他')], default='feature', max_length=10, verbose_name='カテゴリ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='見積(h)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='実績(h)')),
                ('github_issue_url', models.URLField(blank=True, max_length=500, verbose_name='GitHub Issue URL')),
                ('github_pr_url', models.URLField(blank=True, max_length=500, verbose_name='GitHub PR URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dev.devproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '開発タスク',
                'verbose_name_plural': '開発タスク',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('body', models.TextField(verbose_name='本文')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dev.devtask', verbose_name='タスク')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meyasubako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='報告者名')),
                ('kind', models.CharField(choices=[('bug', '不具合'), ('usability', '使いにくい'), ('feature', '機能追加'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('module', models.CharField(choices=[('app', 'アプリ管理'), ('hp', '公式サイト'), ('reserve', '予約管理'), ('dev', '開発'), ('other', 'その他')], max_length=30, verbose_name='対象モジュール')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('problem', models.TextField(verbose_name='困っていること')),
                ('wish', models.TextField(blank=True, verbose_name='こうなってほしい')),
                ('urgency', models.CharField(choices=[('urgent', 'すぐ対応してほしい'), ('not_urgent', '急がない')], default='not_urgent', max_length=20, verbose_name='緊急度')),
                ('screenshot_url', models.URLField(blank=True, max_length=500, verbose_name='スクリーンショット')),
                ('resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meyasubako_posts', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': '目安箱',
                'verbose_name_plural': '目安箱',
                'ordering': ['-created_at'],
            },
        ),
    ]
