# Generated by Django 5.2.17 on 2026-08-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='公開')),
                ('notice_listed', models.BooleanField(default=False, verbose_name='お知らせ一覧に出す')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('delete_reason', models.CharField(blank=True, max_length=255, verbose_name='削除理由')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('notice_listed_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧掲載日時')),
                ('notice_delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧削除日時')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('image_url', models.TextField(blank=True, verbose_name='画像URL')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('event_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='日付')),
                ('title', models.CharField(max_length=255, verbose_name='イベント名')),
                ('detail', models.TextField(blank=True, verbose_name='詳細')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='カラー')),
                ('menu_row', models.IntegerField(blank=True, null=True, verbose_name='対象メニュー行')),
            ],
            options={
                'verbose_name': 'カレンダー',
                'verbose_name_plural': 'カレンダー',
                'ordering': ['-event_on', '-sheet_row'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='公開')),
                ('notice_listed', models.BooleanField(default=False, verbose_name='お知らせ一覧に出す')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('delete_reason', models.CharField(blank=True, max_length=255, verbose_name='削除理由')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('notice_listed_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧掲載日時')),
                ('notice_delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧削除日時')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('image_url', models.TextField(blank=True, verbose_name='画像URL')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('posted_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='投稿日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='カテゴリ')),
                ('icon', models.CharField(blank=True, max_length=16, verbose_name='アイコン絵文字')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('link_url', models.TextField(blank=True, verbose_name='リンクURL')),
                ('link_label', models.CharField(blank=True, max_length=100, verbose_name='リンクボタン名')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='ボタンテキスト')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-posted_on', '-sheet_row'],
            },
        ),
    ]
