# Generated by Django 5.2.17 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='カテゴリ名')),
                ('kind', models.CharField(blank=True, max_length=32, verbose_name='種別')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['sheet_row'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='公開')),
                ('notice_listed', models.BooleanField(default=False, verbose_name='お知らせ一覧に出す')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('delete_reason', models.CharField(blank=True, max_length=255, verbose_name='削除理由')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('notice_listed_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧掲載日時')),
                ('notice_delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧削除日時')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('image_url', models.TextField(blank=True, verbose_name='画像URL')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('registered_on', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('name', models.CharField(max_length=255, verbose_name='メニュー名')),
                ('summary', models.TextField(blank=True, verbose_name='概要説明')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='カテゴリ')),
                ('booking_status', models.CharField(blank=True, max_length=100, verbose_name='予約状況')),
                ('image_urls', models.JSONField(blank=True, default=list, verbose_name='画像URL')),
                ('sort_key', models.BigIntegerField(blank=True, null=True, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
                'ordering': ['-sort_key', 'sheet_row'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, verbose_name='シートの行')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='公開')),
                ('notice_listed', models.BooleanField(default=False, verbose_name='お知らせ一覧に出す')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('delete_reason', models.CharField(blank=True, max_length=255, verbose_name='削除理由')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('notice_listed_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧掲載日時')),
                ('notice_delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='お知らせ一覧削除日時')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('image_url', models.TextField(blank=True, verbose_name='画像URL')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='カテゴリ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格（円）')),
                ('special_price', models.IntegerField(blank=True, null=True, verbose_name='特別価格（円）')),
                ('description', models.TextField(blank=True, verbose_name='商品説明')),
                ('icon_url', models.TextField(blank=True, verbose_name='アイコン')),
                ('description_image_url', models.TextField(blank=True, verbose_name='商品説明画像')),
                ('background_color', models.CharField(blank=True, max_length=32, verbose_name='背景色コード')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('stock_warning', models.IntegerField(blank=True, null=True, verbose_name='在庫警告閾値')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['sheet_row'],
            },
        ),
    ]
