# Generated by Django 5.2.17 on 2026-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_menu_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='日時')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('target_status', models.CharField(blank=True, max_length=100, verbose_name='送信対象')),
                ('target_detail', models.TextField(blank=True, verbose_name='送信対象詳細')),
                ('recipient_count', models.IntegerField(blank=True, null=True, verbose_name='送信件数')),
                ('status', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ステータス')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='配信予定日時')),
                ('target_page', models.CharField(blank=True, max_length=32, verbose_name='対象ページ')),
                ('preview_body', models.TextField(blank=True, verbose_name='プレビュー本文')),
                ('notification_id', models.CharField(blank=True, max_length=64, verbose_name='通知ID')),
                ('result', models.TextField(blank=True, verbose_name='送信結果')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': 'プッシュ通知',
                'verbose_name_plural': 'プッシュ通知',
                'ordering': ['-sheet_row'],
            },
        ),
        migrations.CreateModel(
            name='SupportFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(db_index=True, unique=True, verbose_name='シートの行')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='公開')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='カテゴリ')),
                ('question', models.CharField(max_length=255, verbose_name='質問')),
                ('keywords', models.TextField(blank=True, verbose_name='キーワード')),
                ('answer', models.TextField(blank=True, verbose_name='回答')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '使い方FAQ',
                'verbose_name_plural': '使い方FAQ',
                'ordering': ['-priority', 'sheet_row'],
            },
        ),
    ]
