# Generated by Django 5.2.17 on 2026-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pushnotice_supportfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.CharField(blank=True, help_text='「売切」か「在庫あり」。空欄は在庫あり扱い。', max_length=16, verbose_name='売切状態'),
        ),
    ]
