# Generated by Django 5.2.17 on 2026-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_product_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='カテゴリ'),
        ),
    ]
