# Generated by Django 5.2.17 on 2026-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_calendarevent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='ボタンテキスト'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='link_url',
            field=models.TextField(blank=True, verbose_name='リンクURL'),
        ),
    ]
