# Generated by Django 5.2.17 on 2026-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='氏名')),
                ('kana', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='フリガナ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='電話番号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('avatar_url', models.TextField(blank=True, verbose_name='アイコンURL')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Push設定')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='ご状況')),
                ('stamp_count', models.IntegerField(default=0, verbose_name='現在スタンプ数')),
                ('stamp_card_number', models.IntegerField(default=0, verbose_name='スタンプカード番号')),
                ('last_stamp_at', models.DateTimeField(blank=True, null=True, verbose_name='最終スタンプ取得日時')),
                ('passcode_hash', models.CharField(blank=True, max_length=255, verbose_name='パスコード（ハッシュ）')),
                ('password_hash', models.CharField(blank=True, max_length=255, verbose_name='パスワードハッシュ')),
                ('password_salt', models.CharField(blank=True, max_length=255, verbose_name='パスワードソルト')),
                ('role', models.CharField(blank=True, max_length=32, verbose_name='権限')),
                ('transfer_code', models.CharField(blank=True, max_length=64, verbose_name='引き継ぎコード')),
                ('transfer_code_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='引き継ぎコード発行日時')),
                ('device_sessions', models.JSONField(blank=True, default=list, verbose_name='端末セッション')),
                ('stamp_history', models.JSONField(blank=True, default=list, verbose_name='スタンプ履歴')),
                ('reward_history', models.JSONField(blank=True, default=list, verbose_name='特典履歴')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='削除日時')),
                ('merged_into_id', models.CharField(blank=True, max_length=32, verbose_name='統合先会員ID')),
                ('registration_source', models.CharField(blank=True, max_length=100, verbose_name='登録経路')),
                ('registration_source_detail', models.CharField(blank=True, max_length=255, verbose_name='登録経路詳細')),
                ('registration_source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='登録経路更新日時')),
                ('last_online_at', models.DateTimeField(blank=True, null=True, verbose_name='最終オンライン日時')),
                ('bijiris_registered', models.BooleanField(default=False, verbose_name='ビジリス登録')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '会員',
                'verbose_name_plural': '会員',
                'ordering': ['member_id'],
                'indexes': [models.Index(fields=['name', 'kana'], name='members_mem_name_bb85cc_idx')],
            },
        ),
    ]
