# Generated by Django 5.2.17 on 2026-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='退会'),
        ),
        migrations.AlterField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
    ]
