# Generated by Django 5.2.17 on 2026-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_deleted_alter_member_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='member',
            name='push_subscription',
            field=models.TextField(blank=True, verbose_name='通知の届け先'),
        ),
    ]
