# Generated by Django 5.2.17 on 2026-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_memo_member_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stamp_achieved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='スタンプ達成日時'),
        ),
    ]
