# Generated by Django 5.2.17 on 2026-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_stamp_achieved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reward_admin_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='管理者がスタンプを編集した日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アンケート回答日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_stamp_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='お礼スタンプ付与日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_stamp_pending_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='お礼スタンプ保留日時'),
        ),
    ]
