# Generated by Django 5.2.17 on 2026-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_reward_admin_set_at_member_survey_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='LINEユーザーID'),
        ),
    ]
