# Generated by Django 5.2.17 on 2026-09-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='お名前')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員ID')),
                ('member_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員番号（GAS の記録）')),
                ('name_kana', models.CharField(blank=True, max_length=255, verbose_name='フリガナ')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='別名')),
                ('client_ids', models.JSONField(blank=True, default=list, verbose_name='端末ID')),
                ('active_ticket_card', models.JSONField(blank=True, null=True, verbose_name='回数券カード')),
                ('active_ticket_card_source', models.CharField(blank=True, max_length=16, verbose_name='回数券カードの出どころ')),
                ('last_ticket_card_acquired_at', models.DateTimeField(blank=True, null=True, verbose_name='回数券カードの取得日時')),
                ('measurement_targets', models.JSONField(blank=True, null=True, verbose_name='計測の目標')),
                ('ticket_stamp_adjustment', models.IntegerField(default=0, verbose_name='回数券スタンプの手当て')),
                ('push_status', models.JSONField(blank=True, null=True, verbose_name='通知の状態')),
                ('reward_redemptions', models.JSONField(blank=True, null=True, verbose_name='特典の受け取り')),
                ('admin_managed', models.BooleanField(default=False, verbose_name='受付が作った')),
                ('passcode_hash', models.CharField(blank=True, max_length=128, verbose_name='パスコードのハッシュ')),
                ('passcode_salt', models.CharField(blank=True, max_length=128, verbose_name='パスコードのソルト')),
                ('passcode_updated_at', models.CharField(blank=True, max_length=64, verbose_name='パスコードの更新日時')),
                ('passcode_setup_until', models.CharField(blank=True, max_length=64, verbose_name='再設定の許可期限')),
                ('latest_memo', models.TextField(blank=True, verbose_name='最新のメモ')),
                ('memo_entries', models.JSONField(blank=True, default=list, verbose_name='メモの履歴')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=128, unique=True, verbose_name='アンケートID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('intro_message', models.TextField(blank=True, verbose_name='回答前の案内')),
                ('completion_message', models.TextField(blank=True, verbose_name='回答後の文言')),
                ('status', models.CharField(choices=[('published', '公開中'), ('draft', '下書き'), ('archived', '終了')], db_index=True, default='published', max_length=16, verbose_name='公開状態')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び')),
                ('accepting_responses', models.BooleanField(default=True, verbose_name='回答を受け付ける')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='受付開始')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='受付終了')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='設問')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'verbose_name': 'アンケート',
                'verbose_name_plural': 'アンケート',
                'ordering': ['sort_order', 'survey_id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='回答一覧の行')),
                ('response_id', models.CharField(max_length=128, unique=True, verbose_name='回答ID')),
                ('survey_key', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='アンケートID（GAS）')),
                ('survey_title', models.CharField(blank=True, max_length=255, verbose_name='アンケート名')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='送信日時')),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='端末ID')),
                ('member_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='会員ID')),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='お名前')),
                ('customer_email', models.CharField(blank=True, max_length=255, verbose_name='メールアドレス')),
                ('status', models.CharField(choices=[('new', '未対応'), ('checked', '確認済み'), ('done', '対応済み'), ('trash', 'ゴミ箱')], db_index=True, default='new', max_length=16, verbose_name='対応状況')),
                ('admin_memo', models.TextField(blank=True, verbose_name='管理メモ')),
                ('answers', models.JSONField(blank=True, default=list, verbose_name='回答')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='写真（回答一覧の写真JSON）')),
                ('answers_raw', models.TextField(blank=True, verbose_name='回答（読めなかったもの）')),
                ('files_raw', models.TextField(blank=True, verbose_name='写真（読めなかったもの）')),
                ('managed_at', models.DateTimeField(blank=True, null=True, verbose_name='管理更新日時')),
                ('survey_sheet_row', models.IntegerField(blank=True, null=True, verbose_name='アンケートのシートの行')),
                ('survey_sheet_values', models.JSONField(blank=True, default=dict, verbose_name='アンケートのシートの値')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='bijiris.survey', verbose_name='アンケート')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-submitted_at', '-sheet_row'],
            },
        ),
        migrations.CreateModel(
            name='ResponsePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='設問ID')),
                ('drive_file_id', models.CharField(db_index=True, max_length=128, verbose_name='元の Drive ファイルID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ファイル名')),
                ('mime_type', models.CharField(blank=True, max_length=64, verbose_name='種類')),
                ('captured_at', models.CharField(blank=True, max_length=64, verbose_name='撮影日時（端末の記録）')),
                ('customer_folder_name', models.CharField(blank=True, max_length=255, verbose_name='Drive のお客様フォルダ名')),
                ('folder_name', models.CharField(blank=True, max_length=255, verbose_name='Drive のフォルダ名')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='サーバーの URL')),
                ('order', models.IntegerField(default=0, verbose_name='並び')),
                ('kind', models.CharField(choices=[('before', 'ビフォー'), ('after', 'アフター'), ('other', 'その他')], db_index=True, default='other', max_length=16, verbose_name='種別')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取り込み日時')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bijiris.response', verbose_name='回答')),
            ],
            options={
                'verbose_name': '回答の写真',
                'verbose_name_plural': '回答の写真',
                'ordering': ['response', 'question_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('response', 'question_id', 'drive_file_id'), name='写真は回答と設問とファイルIDで一意')],
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey_key', '-submitted_at'], name='bijiris_res_survey__95863f_idx'),
        ),
    ]
